source "https://rubygems.org"

# Most dependencies come from this gem
gem 'forge-rad20', :require => 'forge-rad', :git => "git@github.com:factore/forge-rad20.git"

# Extra Plugins
gem 'ckeditor', :git => "git@github.com:adriand/ckeditor.git"
gem 'exception_notification', :require => 'exception_notifier'
gem 'launchy'
gem 'nokogiri', '1.5.10'
gem 'pg'

# The Groups
group :development, :test do
  gem 'faker'
  gem 'sqlite3'
end

group :test do
  gem 'capybara', '~> 2.0.0'
  gem 'rspec-rails', '>= 2.0.1'
  gem 'shoulda'
  gem 'shoulda-matchers', '~> 2.0.0'
  gem 'spork', '~> 0.9.0.rc'
  gem 'zentest-without-autotest', '4.4.0'
end

group :darwin do
  gem 'growl'
  gem 'rb-fsevent'
end
