source :rubygems

# Most dependencies come from this gem
gem 'forge-rad', '~> 3.2.12', :require => 'forge-rad'

# Extra Plugins
gem 'exception_notification', :require => 'exception_notifier'
gem 'rails-settings', :git => 'git://github.com/100hz/rails-settings.git'
gem 'launchy'

# The Groups
group :development, :test do
  gem 'faker'
  gem 'sqlite3'
end

group :test do
  gem 'capybara'
  gem 'rspec-rails', '>= 2.0.1'
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'spork', '~> 0.9.0.rc'
  gem 'zentest-without-autotest', '4.4.0'
end

group :assets do
  gem 'coffee-rails'
  gem 'sass-rails'
  gem 'uglifier', ' >= 1.0.3'
end

group :darwin do
  gem 'growl'
  gem 'rb-fsevent'
end